// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAb05sYjkGL3-9OWHLNpTnJGDDZaPiiqfY',
//     appId: '1:246601616094:web:14b05a81d88ce08641504f',
//     messagingSenderId: '246601616094',
//     projectId: 'labtracking-13db4',
//     authDomain: 'labtracking-13db4.firebaseapp.com',
//     storageBucket: 'labtracking-13db4.firebasestorage.app',
//     measurementId: 'G-2WRC67RK74',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCb56_0PRCsdA_OSM96J6Ixa3OU13LhPt8',
//     appId: '1:246601616094:android:784b975d4895c68541504f',
//     messagingSenderId: '246601616094',
//     projectId: 'labtracking-13db4',
//     storageBucket: 'labtracking-13db4.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCL1q9so3-_2DpgFoEltuPiwWOEzBxK5yE',
//     appId: '1:246601616094:ios:053b20fd5d0ab22a41504f',
//     messagingSenderId: '246601616094',
//     projectId: 'labtracking-13db4',
//     storageBucket: 'labtracking-13db4.firebasestorage.app',
//     iosClientId: '246601616094-pidb07r9ti1t49hdu413btciunelntov.apps.googleusercontent.com',
//     iosBundleId: 'com.example.labtracking',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCL1q9so3-_2DpgFoEltuPiwWOEzBxK5yE',
//     appId: '1:246601616094:ios:053b20fd5d0ab22a41504f',
//     messagingSenderId: '246601616094',
//     projectId: 'labtracking-13db4',
//     storageBucket: 'labtracking-13db4.firebasestorage.app',
//     iosClientId: '246601616094-pidb07r9ti1t49hdu413btciunelntov.apps.googleusercontent.com',
//     iosBundleId: 'com.example.labtracking',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAb05sYjkGL3-9OWHLNpTnJGDDZaPiiqfY',
//     appId: '1:246601616094:web:30960d2edc7f9c8541504f',
//     messagingSenderId: '246601616094',
//     projectId: 'labtracking-13db4',
//     authDomain: 'labtracking-13db4.firebaseapp.com',
//     storageBucket: 'labtracking-13db4.firebasestorage.app',
//     measurementId: 'G-94Z1D4SGVP',
//   );

// }
