// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnQxoie9pOEVnccMorCSevA6-5YskWJyc',
    appId: '1:474380365235:web:85cfdc290c05820c672fc6',
    messagingSenderId: '474380365235',
    projectId: 'labtracking-94b0c',
    authDomain: 'labtracking-94b0c.firebaseapp.com',
    storageBucket: 'labtracking-94b0c.firebasestorage.app',
    measurementId: 'G-J1RW8QBLD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH4tg8AEsSEFx7VxIebO7DhXs7QI5OG6k',
    appId: '1:474380365235:android:e00ec32b9d1662b4672fc6',
    messagingSenderId: '474380365235',
    projectId: 'labtracking-94b0c',
    storageBucket: 'labtracking-94b0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYlBFo_7xQ7muOnkYA_M7dfBQ2bKcGTM4',
    appId: '1:474380365235:ios:c43e59b4f1003768672fc6',
    messagingSenderId: '474380365235',
    projectId: 'labtracking-94b0c',
    storageBucket: 'labtracking-94b0c.firebasestorage.app',
    androidClientId: '474380365235-egvjs6mukkev0sm1hkqdv23f9d3d2mv0.apps.googleusercontent.com',
    iosClientId: '474380365235-gam566cihfbdjiv1cue3teajg4u40h0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.labtracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYlBFo_7xQ7muOnkYA_M7dfBQ2bKcGTM4',
    appId: '1:474380365235:ios:c43e59b4f1003768672fc6',
    messagingSenderId: '474380365235',
    projectId: 'labtracking-94b0c',
    storageBucket: 'labtracking-94b0c.firebasestorage.app',
    androidClientId: '474380365235-egvjs6mukkev0sm1hkqdv23f9d3d2mv0.apps.googleusercontent.com',
    iosClientId: '474380365235-gam566cihfbdjiv1cue3teajg4u40h0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.labtracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDufjLpRLL32AjOewvzuAyd112Fib2eZb0',
    appId: '1:474380365235:web:50b68a49fa013e15672fc6',
    messagingSenderId: '474380365235',
    projectId: 'labtracking-94b0c',
    authDomain: 'labtracking-94b0c.firebaseapp.com',
    storageBucket: 'labtracking-94b0c.firebasestorage.app',
    measurementId: 'G-MNS81MTJDZ',
  );

}