// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMbX7K35LAroI70LJE8PzNp3ndzEbUfCA',
    appId: '1:1023520266966:web:bae6010ed42421cef90777',
    messagingSenderId: '1023520266966',
    projectId: 'labtracking-982fa',
    authDomain: 'labtracking-982fa.firebaseapp.com',
    storageBucket: 'labtracking-982fa.appspot.com',
    measurementId: 'G-074CX4M30E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr2V8uwvY7FYJaMPehAVVLAszUod62mtA',
    appId: '1:1023520266966:android:8dab66ddf6784b9cf90777',
    messagingSenderId: '1023520266966',
    projectId: 'labtracking-982fa',
    storageBucket: 'labtracking-982fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFTPJX_ajwWXQkrynmnxIiXEGmYsquTT4',
    appId: '1:1023520266966:ios:cfb05abf3e36e2cdf90777',
    messagingSenderId: '1023520266966',
    projectId: 'labtracking-982fa',
    storageBucket: 'labtracking-982fa.appspot.com',
    iosBundleId: 'com.example.labtracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFTPJX_ajwWXQkrynmnxIiXEGmYsquTT4',
    appId: '1:1023520266966:ios:d029068b0be291a9f90777',
    messagingSenderId: '1023520266966',
    projectId: 'labtracking-982fa',
    storageBucket: 'labtracking-982fa.appspot.com',
    iosBundleId: 'com.example.labtracking.RunnerTests',
  );
}
